name: tazkrtak
description: A new secure way for paying your transportation tickets.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  base32: ^1.0.1
  cloud_firestore: ^0.12.9
  crypto: ^2.0.6
  cupertino_icons: ^0.1.2
  equatable: ^0.2.0
  flutter_bloc: ^0.21.0
  flutter_circular_chart: ^0.1.0
  holding_gesture: ^0.0.3
  intl: ^0.15.8
  meta: ^1.1.6
  percent_indicator: ^2.1.1
  qr_flutter: ^3.0.1
  shared_preferences: 0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - lang/en.json
    - lang/ar.json

    
    
                                      